#!/usr/bin/env python3

# I want to run the shell to trigger the submake. The shell can interpret the
# args then call the $(MAKE).
#
# I communicate the shell interpretted args to the parent simply through
# stdout. The parent pymake process will read the individual args line by line.

import sys

for s in sys.argv:
    print("%s" % s)


